# -*- coding: utf-8 -*-
"""Mapas_Boxplots.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Y1yqchC-GXFSgV4sCboSDpo0E7S_7kuw
"""

import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import seaborn as sns

x= np.linspace(0,10,num=100)
a=5
b=5
y=x*a+b
y2= x*0.5+3

fig= plt.figure(figsize=(5,5))

plt.plot(x,y, color= "b", label="Linea Y")
plt.plot(x, y2, color="r", label= "Line Y2")

plt.xlabel("x")
plt.ylabel("y")
plt.title("Lineas diagonales")

plt.legend(loc= "best")
plt.grid(True)

df= pd.read_csv("peso_estatura_genero.csv")

x= np.linspace(0,10,num=30)
a=5
b=5
y=x*a+b
y2= x*0.5+3

fig= plt.figure(figsize=(5,5))

plt.scatter(df["Estatura"],df["Peso"], marker= "^", label= "Correlación") #Usando esta funnción, graifca puntos en vez de líneas.

plt.xlabel("x")
plt.ylabel("y")
plt.title("Lineas diagonales")

plt.legend(loc= "best")
plt.grid(True)

df= pd.read_csv("iris.csv")

fig= plt.figure()

sns.countplot(data=df, y= "Species")

plt.xlabel("Conteo")
plt.ylabel("Especie")
plt.title("Conteo de Especies")

df_prueba= pd.DataFrame(data= {"Ciudad": ["Hermosillo", "Aguascalientes", "Mérida", "Querétaro", "Tepic", "Acapulco"], "Gusto": [10,9.9,9,8,5.9,3.5]})

df_prueba.set_index("Ciudad")["Gusto"].plot(kind= "bar")

df_prueba.set_index("Ciudad")["Gusto"].plot(kind= "area")

df_prueba.set_index("Ciudad")["Gusto"].plot.barh()

df_prueba.set_index("Ciudad")["Gusto"].plot.pie()

sns.histplot(data=df, x= "Petal.Length")

plt.xlabel("Especies")
plt.ylabel("Frecuencia")
plt.title("Histograma de especies")

sns.histplot(data=df, x= "Petal.Length", hue= "Species", bins=20, kde= True)

plt.xlabel("Especies")
plt.ylabel("Frecuencia")
plt.title("Histograma de especies")

sns.scatterplot(data=df, x= "Petal.Length",y= "Petal.Width", hue= "Species")

plt.xlabel("Especies")
plt.ylabel("Frecuencia")
plt.title("Histograma de especies")

sns.pairplot(data=df,hue= "Species") #el hue especies es para siempre tener una variable cualitativa con la cual trabajar

plt.xlabel("Especies")
plt.ylabel("Frecuencia")
plt.title("Histograma de especies")

corr= df.corr()
sns.heatmap(data=corr, vmin= -1, vmax= 1, cmap="Blues")

fig= plt.figure(figsize=(10,3))

sns.boxplot(data= df, x= "Sepal.Width", y="Species")

"""Responde las siguientes preguntas:

¿Hay alguna variable que no aporta información? creo que en esta base de datos todas las variables aportan informacion

Si tuvieras que eliminar variables, ¿cuáles quitarías y por qué? No quitaria ninguna ya que al ser pocas variables y al todas tener relacion no se elimina ninguna

¿Existen variables que tengan datos extraños?
En este caso no es asi

Si comparas las variables, ¿todas están en rangos similares? ¿Crees que esto afecte? Estan en rangos similares esto ayuda a que el analisis del dato quede mejor establecido ya que son datos mas relacionados

¿Puedes encontrar grupos qué se parezcan? ¿Qué grupos son estos? en este caso no ya que todos suelen tener comportamientos distintos.
"""